fixed the inconsistent parameter name in run_circuitset_and_measure
zapatacomputing/qe-qiskit pull request #72
Opened 2021-11-04 20:16 UTC by aakunitsa

I am submitting this PR because having different parameter names (`circuits` vs `circuitset`) between for the  **same method** (`run_circuitset_and_measure`) in `QiskitBackend` and `QiskitSimulator` (unless there is a good reason that I'm not aware of) is driving me crazy. Sorry :)

2021-11-04 20:20 UTC, mstechly requested changes
@aakunitsa good catch! Just please fix `circuitset` in the rest of this function as well, as it will fail now.

2021-11-04 20:29 UTC, aakunitsa commented
I did it locally, but forgot to push the changes, will do it in a sec!

2021-11-04 20:50 UTC, aakunitsa commented
@mstechly Could you please merge and delete the branch if everything looks good? 🙏

2021-11-05 12:50 UTC, mstechly approved these changes

2021-11-05 12:51 UTC, merged