Hotfix assert list
zapatacomputing/qe-qiskit pull request #76
Opened 2021-11-30 15:22 UTC by jgonthier

In `z-quantum-core`, the list of circuits and shots are [built as tuples, not lists](https://github.com/zapatacomputing/z-quantum-core/blob/5a464b9efcd06173781bb713f40286a5d0791eae/src/python/zquantum/core/estimation/_estimation.py#L315-L322), which caused problems with this assertion. Not sure if the best fix is to add `tuple` to the assertion like I did or change `z-quantum-core` to build lists instead.

2021-12-01 00:12 UTC, max-radin requested changes
Thanks for catching this @jgonthier! I think we should actually just get rid of these two assertions. In general it's preferable to use type hints to discover type errors before execution rather than making assertions at runtime.

I'm guessing the assertions were originally added because, a long time ago, `n_samples` was supposed to be an integer, and then we later changed it to be a list of integers. I think the assertions were added to catch errors related to that change. But that shouldn't be a big problem anymore since it was many months ago.

Also it looks like the type hints for the qiskit backend (as well as backend base class) are not quite right. Many functions have `List` when they should really be `Iterable`, which includes `List` and `Tuple`. I'll add a story about that and we can address it in separate PRs. (The problems with type hints won't stop anyone from running their code, it will just make type checkers unhappy.)

2021-12-01 20:20 UTC, jgonthier commented
Assertions were deleted as discussed.

2021-12-01 20:35 UTC, max-radin approved these changes

2021-12-02 23:54 UTC, merged

2021-12-02 23:54 UTC, jgonthier commented
Merged, please de not delete the branch yet.