Workflow v1
zapatacomputing/qe-qiskit pull request #8
Opened 2020-10-01 20:47 UTC by simonwa7

2020-10-05 18:10 UTC, martamau requested changes

2020-10-05 18:10 UTC, martamau commented on testing/v1/workflows/get-qiskit-noise-model.yaml
> +    branch: "workflow-v1"
should be 'dev' :)

2020-10-05 18:47 UTC, simonwa7 commented on testing/v1/workflows/get-qiskit-noise-model.yaml
> +    branch: "workflow-v1"
Addressed here: 
a60cf4f

2020-10-14 19:30 UTC, martamau approved these changes

2020-10-14 19:30 UTC, merged